# wee test
PORT=/dev/ttyUSB0
SPEED=115200

all:
	@echo "Usage: make install"

install:
#	ampy --port $(PORT) --baud $(SPEED) put dht22.py
#	ampy --port $(PORT) --baud $(SPEED) put main.py
#	ampy --port $(PORT) --baud $(SPEED) put dhtsock.py
#	ampy --port $(PORT) --baud $(SPEED) rm dht22.py
	ampy --port $(PORT) --baud $(SPEED) put main.py
#	ampy --port $(PORT) --baud $(SPEED) rm dhtsock.py
